In [21]:
%matplotlib notebook
from matplotlib import pyplot as plt
from keras.models import Model, Sequential
from keras.layers import Dense
from keras.layers import Input, Merge
from keras.activations import relu, tanh, sigmoid, softmax
from keras.optimizers import Adam, SGD
from scipy.stats import norm
import numpy as np

# Data Extraction - Gaussian
data = 3G(0, 1) + 2G(3, 2) + 5G(-5, 3)

In [35]:
# def create_gaussian_mixture(n, x_range):
#     x = (x_range * np.random.rand(n)) - (x_range / 2.0)
#     pdf = lambda x: 3*norm.pdf(x, loc=0, scale=1) + 2*norm.pdf(x, loc=3, scale=2) + 5*norm.pdf(x, loc=-5, scale=3)
#     y = pdf(x)
#     return x, y

# # Sample waveform
# x, y = create_gaussian_mixture(1000, 30)
# plt.scatter(x, y)

In [11]:
n_train = 1000
n_test = 200
n_samples = n_train + n_test
X = np.linspace(-n_samples/2.0, n_samples/2.0, n_samples) + 0.01*np.random.rand(n_samples) # noise (z)
X = X[np.random.permutation(n_samples)] # randomize the noise
Y = np.random.normal(size=n_train + n_test) # data (x)
(X_train, Y_train), (X_test, Y_test) = (X[:n_train], Y[:n_train]), (X[n_train:], Y[n_train:])

In [12]:
print(X_train.shape, X_train[0])
print(Y_train.shape, Y_train[0])
print(X_test.shape, X_test[0])
print(Y_test.shape, Y_test[0])

(1000,) 59.5566225988
(1000,) 1.51096381949
(200,) -347.781290577
(200,) 0.54375781295


# Model Parameters

# Generative Model

In [16]:
G = Sequential()
G.add(Dense(32, input_dim=1))
G.add(Dense(32))
G.add(Dense(1))
G.compile(loss='binary_crossentropy', optimizer=Adam())
G.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
dense_6 (Dense)                  (None, 32)            64          dense_input_3[0][0]              
____________________________________________________________________________________________________
dense_7 (Dense)                  (None, 32)            1056        dense_6[0][0]                    
____________________________________________________________________________________________________
dense_8 (Dense)                  (None, 1)             33          dense_7[0][0]                    
Total params: 1,153
Trainable params: 1,153
Non-trainable params: 0
____________________________________________________________________________________________________


# Discrimator

In [14]:
D = Sequential()
D.add(Dense(32, input_dim=1))
D.add(Dense(32, input_dim=1))
D.add(Dense(1))
D.compile(loss='categorical_crossentropy', optimizer=Adam())
D.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
dense_3 (Dense)                  (None, 32)            64          dense_input_2[0][0]              
____________________________________________________________________________________________________
dense_4 (Dense)                  (None, 32)            1056        dense_3[0][0]                    
____________________________________________________________________________________________________
dense_5 (Dense)                  (None, 1)             33          dense_4[0][0]                    
Total params: 1,153
Trainable params: 1,153
Non-trainable params: 0
____________________________________________________________________________________________________


In [25]:
gan_input = Input(shape=[1])
gan_net = D(G(gan_input))
GAN = Model(gan_input, gan_net)
GAN.compile(loss='categorical_crossentropy', optimizer=Adam())
GAN.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
input_4 (InputLayer)             (None, 1)             0                                            
____________________________________________________________________________________________________
sequential_3 (Sequential)        (None, 1)             1153        input_4[0][0]                    
____________________________________________________________________________________________________
sequential_2 (Sequential)        (None, 1)             1153        sequential_3[4][0]               
Total params: 2,306
Trainable params: 2,306
Non-trainable params: 0
____________________________________________________________________________________________________


array([8, 1, 2, 6, 4, 0, 5, 7, 9, 3])

In [8]:
order = np.random.permutation(10)
arange = np.arange(10)
print(order)
print(arange)
print(arange[order])

[1 5 4 0 3 7 9 6 2 8]
[0 1 2 3 4 5 6 7 8 9]
[1 5 4 0 3 7 9 6 2 8]
